version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - FirebaseProjectId=${FirebaseProjectId}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - ChatterlyConnectionString=${ChatterlyConnectionString}
      - ChatterlyJWTKey=${ChatterlyJWTKey}
      - ChatterlyIssuer=${ChatterlyIssuer}
      - ChatterlyAudience=${ChatterlyAudience}
      - ChatterlySMTPUsername=${ChatterlySMTPUsername}
      - ChatterlySMTPPassword=${ChatterlySMTPPassword}
      - ChatterlyJWTExpiresInMinutes=${ChatterlyJWTExpiresInMinutes}
      - ChatterlyRefreshTokenExpiresInDays=${ChatterlyRefreshTokenExpiresInDays}
    depends_on:
      - db
    networks:
      - backend-network

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    ports:
      - "4888:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend-network

volumes:
  db-data:

networks:
  backend-network:
